### PR TITLE
Add support for GetterProperty and SetterProperty

### LINKED ISSUE #6: GetterProperty and SetterProperty aren't handled correctly
GetterProperty and SetterProperty aren't turned to their babel ObjectMethod equivalent.
NOTE: I almost have PR ready to publish

### PR DESCRIPTION
**Pull request by Markos-Th09**
Closes #6

### CODE REVIEW

**Comment by Markos-Th09** [comment]
Hmm why did the action fail?

**Comment by coderaiser** [comment]
Could you please update docs?

**Comment by Markos-Th09** [comment]
> Could you please update docs?

ok

**Comment by coderaiser** [comment]
Thanks 🎉 !

**Comment by coderaiser** [comment]
Landed in [v1.23.0](https://github.com/coderaiser/swc-to-babel/releases/tag/v1.23.0) 🎂!

**Pull request merged**
